### ISSUE TITLE
WebAssembly.instantiate(): invalid value type 's128', enable with --experimental-wasm-simd @+653). Build with -s ASSERTIONS=1 for more info.

### ISSUE THREAD

**Issue by hxg-ai** [nihui/ncnn-webassembly-yolov5#4]
我在浏览器中运行样例的时候遇到了如下的错误，自己编译完之后的模型运行也是这种情况，不知道怎么解决了，能不能帮我看一下
错误情况如下：

yolov5.js:1 Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): invalid value type 's128', enable with --experimental-wasm-simd @+653). Build with -s ASSERTIONS=1 for more info.
    at abort (http://127.0.0.1:8899/yolov5.js:1:18831)
    at http://127.0.0.1:8899/yolov5.js:1:20818
abort @ yolov5.js:1
(anonymous) @ yolov5.js:1
Promise.then (async)
instantiateArrayBuffer @ yolov5.js:1
instantiateAsync @ yolov5.js:1
createWasm @ yolov5.js:1
(anonymous) @ yolov5.js:1
yolov5.js:1 Uncaught TypeError: Cannot read property 'malloc' of undefined
    at Module._malloc (yolov5.js:1)
    at HTMLVideoElement.<anonymous> (camera.html:94)

**Comment by hxg-ai** [comment]
浏览器更新为最新

**Comment by eivaltsec** [comment]
> 浏览器更新为最新

大佬这个问题解决了么？用的是最新版的谷歌浏览器就可以了么？

**Comment by Altai01** [comment]
Uncaught RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (yolov5up.js:1:16875)
    at _abort (yolov5up.js:1:75217)
    at 002b53f2:0xa154c
    at 002b53f2:0x2ab7
    at 002b53f2:0xeec
    at Module.___wasm_call_ctors (yolov5up.js:1:78988)
    at func (yolov5up.js:1:78306)
    at callRuntimeCallbacks (yolov5up.js:1:19777)
    at initRuntime (yolov5up.js:1:15472)
    at doRun (yolov5up.js:1:81494)
有这个问题
